[package]
name = "parameters"
description = "Automatic replace variables in configuration file templates from environment variables."
version = "0.0.0-dev"
license = "MIT"
authors = ["Christian Mayer <christian@fox21.at>"]
homepage = "https://github.com/TheFox/parameters-rust"
documentation = "https://github.com/TheFox/parameters-rust"
repository = "https://github.com/TheFox/parameters-rust"
keywords = ["env", "variables"]
categories = ["cli", "configuration"]
edition = "2018"

[dependencies]

[profile.release]
panic = 'abort'

[[bin]]
name = "parameters"
path = "src/main.rs"
